version: '2'

services:
  app:
    extends:
      file: env.yml
      service: env
    build: .
    image: golang:1.7.4-alpine
    ports:
      - "8008:8008"
    volumes:
      - ./:/go/src/github.com/andreiavrammsd/microservices-persistent-communication
    depends_on:
      - "queue"
    restart: unless-stopped
    command: ["./wait-for-it.sh", "-h", "queue", "-p", "5672", "-c", "/go/bin/microservices-persistent-communication", "-q", "-t", "300"]
  queue:
    extends:
      file: env.yml
      service: env
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    expose:
      - "5672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
