version: '2'

services:
  app:
    build: .
    image: golang:1.7.4-alpine
    ports:
      - "8008:8008"
    volumes:
      - ./:/go/src/github.com/andreiavrammsd/microservices-persistent-communication
    depends_on:
      - "queue"
    restart: unless-stopped
    command: ["./wait-for-it.sh", "-h", "queue", "-p", "5672", "-c", "/go/bin/microservices-persistent-communication", "-q", "-t", "300"]
  queue:
    image: rabbitmq:3-management
    environment:
        RABBITMQ_DEFAULT_USER: "WhLSCKgkzL66aAvQ"
        RABBITMQ_DEFAULT_PASS: "Ayxae5yNGUtQVSufkp44xPgTJpaBeQKS"
        RABBITMQ_DEFAULT_VHOST: "/"
        RABBITMQ_HIPE_COMPILE: 1
    ports:
      - "15672:15672"
    expose:
      - "5672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
